### ISSUE TITLE
Commented markup

### ISSUE THREAD

**Issue by kepop1** [Cratesy/quiz_game#1]
https://github.com/Cratesy/quiz_game/blob/d7fb1615ccf54f6c6a1cef7c5319c6ae660e3fff/high-score.html#L46-L96
https://github.com/Cratesy/quiz_game/blob/d7fb1615ccf54f6c6a1cef7c5319c6ae660e3fff/assets/css/style.css#L47-L66
Can probably delete this 😁

**Comment by Shubham56-droid** [comment]
i will do it  pls  assign  issue  to me

**Comment by Cratesy** [comment]
fixed and sorted
