### ISSUE TITLE
CSS Properties

### ISSUE THREAD

**Issue by kepop1** [Cratesy/quiz_game#2]
https://github.com/Cratesy/quiz_game/blob/d7fb1615ccf54f6c6a1cef7c5319c6ae660e3fff/assets/css/style.css#L26

Some bad property syntax here which is probably why the timer looks so teeny 😁

**Comment by Shubham56-droid** [comment]
i will do it pls  assign issue  to me

**Comment by Cratesy** [comment]
sorted thanks ken was typo
